# Generated by Django 5.2.10 on 2026-01-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_gtfs_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='catalog.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_gtfs_id', models.CharField(max_length=128)),
                ('short_name', models.CharField(blank=True, max_length=64)),
                ('long_name', models.CharField(blank=True, max_length=255)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtfs.agency')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='catalog.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_gtfs_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='catalog.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_gtfs_id', models.CharField(max_length=128)),
                ('service_id', models.CharField(blank=True, max_length=128)),
                ('headsign', models.CharField(blank=True, max_length=255)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='catalog.feed')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='gtfs.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.PositiveIntegerField()),
                ('arrival_time', models.CharField(blank=True, max_length=16)),
                ('departure_time', models.CharField(blank=True, max_length=16)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='gtfs.trip')),
            ],
            options={
                'ordering': ['trip_id', 'stop_sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('feed', 'agency_gtfs_id'), name='uniq_agency_per_feed'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('feed', 'route_gtfs_id'), name='uniq_route_per_feed'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('feed', 'stop_gtfs_id'), name='uniq_stop_per_feed'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('feed', 'trip_gtfs_id'), name='uniq_trip_per_feed'),
        ),
        migrations.AddConstraint(
            model_name='stoptime',
            constraint=models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='uniq_stopseq_per_trip'),
        ),
    ]
