# Generated by Django 5.2.10 on 2026-01-25 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('gtfs_zip_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.feed')),
            ],
        ),
    ]
